export const VIETNAM_CITIES = [
    { value: "all", label: "Tất cả thành phố" },
    { value: "Hà Nội", label: "Hà Nội" },
    { value: "Hồ Chí Minh", label: "Hồ Chí Minh" },
    { value: "Đà Nẵng", label: "Đà Nẵng" },
    { value: "Cần Thơ", label: "Cần Thơ" },
    { value: "Hải Phòng", label: "Hải Phòng" },
    { value: "An Giang", label: "An Giang" },
    { value: "Bà Rịa-Vũng Tàu", label: "Bà Rịa-Vũng Tàu" },
    { value: "Bắc Giang", label: "Bắc Giang" },
    { value: "Bắc Kạn", label: "Bắc Kạn" },
    { value: "Bạc Liêu", label: "Bạc Liêu" },
    { value: "Bến Tre", label: "Bến Tre" },
    { value: "Bình Dương", label: "Bình Dương" },
    { value: "Bình Định", label: "Bình Định" },
    { value: "Bình Phước", label: "Bình Phước" },
    { value: "Bình Thuận", label: "Bình Thuận" },
    { value: "Cao Bằng", label: "Cao Bằng" },
    { value: "Cà Mau", label: "Cà Mau" },
    { value: "Đắk Lắk", label: "Đắk Lắk" },
    { value: "Đắk Nông", label: "Đắk Nông" },
    { value: "Điện Biên", label: "Điện Biên" },
    { value: "Đồng Nai", label: "Đồng Nai" },
    { value: "Đồng Tháp", label: "Đồng Tháp" },
    { value: "Gia Lai", label: "Gia Lai" },
    { value: "Hà Giang", label: "Hà Giang" },
    { value: "Hà Nam", label: "Hà Nam" },
    { value: "Hà Tĩnh", label: "Hà Tĩnh" },
    { value: "Hải Dương", label: "Hải Dương" },
    { value: "Hòa Bình", label: "Hòa Bình" },
    { value: "Hưng Yên", label: "Hưng Yên" },
    { value: "Khánh Hòa", label: "Khánh Hòa" },
    { value: "Kiên Giang", label: "Kiên Giang" },
    { value: "Kon Tum", label: "Kon Tum" },
    { value: "Lai Châu", label: "Lai Châu" },
    { value: "Lâm Đồng", label: "Lâm Đồng" },
    { value: "Lạng Sơn", label: "Lạng Sơn" },
    { value: "Lào Cai", label: "Lào Cai" },
    { value: "Long An", label: "Long An" },
    { value: "Nam Định", label: "Nam Định" },
    { value: "Nghệ An", label: "Nghệ An" },
    { value: "Ninh Bình", label: "Ninh Bình" },
    { value: "Ninh Thuận", label: "Ninh Thuận" },
    { value: "Phú Thọ", label: "Phú Thọ" },
    { value: "Phú Yên", label: "Phú Yên" },
    { value: "Quảng Bình", label: "Quảng Bình" },
    { value: "Quảng Nam", label: "Quảng Nam" },
    { value: "Quảng Ngãi", label: "Quảng Ngãi" },
    { value: "Quảng Ninh", label: "Quảng Ninh" },
    { value: "Quảng Trị", label: "Quảng Trị" },
    { value: "Sóc Trăng", label: "Sóc Trăng" },
    { value: "Sơn La", label: "Sơn La" },
    { value: "Tây Ninh", label: "Tây Ninh" },
    { value: "Thái Bình", label: "Thái Bình" },
    { value: "Thái Nguyên", label: "Thái Nguyên" },
    { value: "Thanh Hóa", label: "Thanh Hóa" },
    { value: "Thừa Thiên-Huế", label: "Thừa Thiên-Huế" },
    { value: "Tiền Giang", label: "Tiền Giang" },
    { value: "Trà Vinh", label: "Trà Vinh" },
    { value: "Tuyên Quang", label: "Tuyên Quang" },
    { value: "Vĩnh Long", label: "Vĩnh Long" },
    { value: "Vĩnh Phúc", label: "Vĩnh Phúc" },
    { value: "Yên Bái", label: "Yên Bái" },
    { value: "Khác", label: "others" },
    { value: "Quốc tế", label: "Quốc tế" },
    
  ];
export const GENDER_OPTIONS = [
    { value: "Nam", label: <span>Nam</span> },
    { value: "Nữ", label: <span>Nữ</span> },
    { value: "Khác", label: <span>Khác</span> },
];
export const COMPANY_IMAGE_URL = [
  { name: "mb-bank", url: "MBLOGO.webp" },
  { name: "scandinavian-software-park", url: "ScandinavianLOGO.webp" },
  { name: "one-tech-stop-vietnam-company-ltd", url: "OTSVLOGO.webp" },
  { name: "mcredit-cong-ty-tai-chinh-tnhh-mb-shinsei", url: "MCREDITLOGO.webp" },
  { name: "tymex", url: "TYMEXLOGO.webp" },
  { name: "andpad-vietnam-co-ltd", url: "ANDPADLOGO.webp" },
  { name: "employment-hero", url: "EmploymentHeroLOGO.webp" },
  { name: "bosch-global-software-technologies-company-limited", url: "BoschLOGO.webp" },
  { name: "ssi-securities-corporation", url: "SSILOGO.webp" },
];
