#profile prod
server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
app:
  mail:
    from: ${MAIL_FROM:no-reply@itviec.com}
application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_ACCESS_EXP_MS}
      refresh-token:
        expiration: ${JWT_REFRESH_EXP_MS}
    cookie:
      secure: true
      same-site: Lax
